'use strict';
// ─────────────────────────────────────────────────────────
//  VOCABPACKS.JS  –  Packs de vocabulario libre
//  IDs: p001 … p205
// ─────────────────────────────────────────────────────────

const VOCAB_PACKS = [

  // ─────────────────────────────────────────────────────
  //  NÚMEROS  (p001 – p030)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-numbers',
    title: 'Números',
    icon: '🔢',
    color: '#1cb0f6',
    colorDark: '#0a85c0',
    desc: 'Del 21 al 1000 · Ordinales',
    vocabulary: [
      { id: 'p001', en: 'twenty-one',    es: 'veintiuno'     },
      { id: 'p002', en: 'twenty-two',    es: 'veintidós'     },
      { id: 'p003', en: 'thirty',        es: 'treinta'       },
      { id: 'p004', en: 'forty',         es: 'cuarenta'      },
      { id: 'p005', en: 'fifty',         es: 'cincuenta'     },
      { id: 'p006', en: 'sixty',         es: 'sesenta'       },
      { id: 'p007', en: 'seventy',       es: 'setenta'       },
      { id: 'p008', en: 'eighty',        es: 'ochenta'       },
      { id: 'p009', en: 'ninety',        es: 'noventa'       },
      { id: 'p010', en: 'one hundred',   es: 'cien'          },
      { id: 'p011', en: 'two hundred',   es: 'doscientos'    },
      { id: 'p012', en: 'five hundred',  es: 'quinientos'    },
      { id: 'p013', en: 'one thousand',  es: 'mil'           },
      { id: 'p014', en: 'first',         es: 'primero'       },
      { id: 'p015', en: 'second',        es: 'segundo'       },
      { id: 'p016', en: 'third',         es: 'tercero'       },
      { id: 'p017', en: 'fourth',        es: 'cuarto'        },
      { id: 'p018', en: 'fifth',         es: 'quinto'        },
      { id: 'p019', en: 'sixth',         es: 'sexto'         },
      { id: 'p020', en: 'seventh',       es: 'séptimo'       },
      { id: 'p021', en: 'eighth',        es: 'octavo'        },
      { id: 'p022', en: 'ninth',         es: 'noveno'        },
      { id: 'p023', en: 'tenth',         es: 'décimo'        },
      { id: 'p024', en: 'zero',          es: 'cero'          },
      { id: 'p025', en: 'a dozen',       es: 'una docena'    },
      { id: 'p026', en: 'a half',        es: 'la mitad'      },
      { id: 'p027', en: 'a quarter',     es: 'un cuarto'     },
      { id: 'p028', en: 'double',        es: 'el doble'      },
      { id: 'p029', en: 'triple',        es: 'el triple'     },
      { id: 'p030', en: 'both',          es: 'ambos'         },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  ANIMALES  (p031 – p050)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-animals',
    title: 'Animales',
    icon: '🦁',
    color: '#ff9600',
    colorDark: '#d47000',
    desc: 'Salvajes y domésticos',
    vocabulary: [
      { id: 'p031', en: 'lion',      es: 'león'      },
      { id: 'p032', en: 'tiger',     es: 'tigre'     },
      { id: 'p033', en: 'elephant',  es: 'elefante'  },
      { id: 'p034', en: 'giraffe',   es: 'jirafa'    },
      { id: 'p035', en: 'monkey',    es: 'mono'      },
      { id: 'p036', en: 'bear',      es: 'oso'       },
      { id: 'p037', en: 'wolf',      es: 'lobo'      },
      { id: 'p038', en: 'fox',       es: 'zorro'     },
      { id: 'p039', en: 'rabbit',    es: 'conejo'    },
      { id: 'p040', en: 'mouse',     es: 'ratón'     },
      { id: 'p041', en: 'horse',     es: 'caballo'   },
      { id: 'p042', en: 'cow',       es: 'vaca'      },
      { id: 'p043', en: 'sheep',     es: 'oveja'     },
      { id: 'p044', en: 'pig',       es: 'cerdo'     },
      { id: 'p045', en: 'shark',     es: 'tiburón'   },
      { id: 'p046', en: 'whale',     es: 'ballena'   },
      { id: 'p047', en: 'eagle',     es: 'águila'    },
      { id: 'p048', en: 'snake',     es: 'serpiente' },
      { id: 'p049', en: 'butterfly', es: 'mariposa'  },
      { id: 'p050', en: 'dolphin',   es: 'delfín'    },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  FINANZAS  (p051 – p070)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-finance',
    title: 'Finanzas',
    icon: '💰',
    color: '#58cc02',
    colorDark: '#3d9900',
    desc: 'Dinero · Inversiones · Economía',
    vocabulary: [
      { id: 'p051', en: 'bank',        es: 'banco'           },
      { id: 'p052', en: 'loan',        es: 'préstamo'        },
      { id: 'p053', en: 'mortgage',    es: 'hipoteca'        },
      { id: 'p054', en: 'investment',  es: 'inversión'       },
      { id: 'p055', en: 'savings',     es: 'ahorros'         },
      { id: 'p056', en: 'debt',        es: 'deuda'           },
      { id: 'p057', en: 'interest',    es: 'interés'         },
      { id: 'p058', en: 'credit',      es: 'crédito'         },
      { id: 'p059', en: 'dividend',    es: 'dividendo'       },
      { id: 'p060', en: 'stock',       es: 'acción'          },
      { id: 'p061', en: 'bond',        es: 'bono'            },
      { id: 'p062', en: 'budget',      es: 'presupuesto'     },
      { id: 'p063', en: 'profit',      es: 'ganancia'        },
      { id: 'p064', en: 'loss',        es: 'pérdida'         },
      { id: 'p065', en: 'revenue',     es: 'ingresos'        },
      { id: 'p066', en: 'expense',     es: 'gasto'           },
      { id: 'p067', en: 'asset',       es: 'activo'          },
      { id: 'p068', en: 'inflation',   es: 'inflación'       },
      { id: 'p069', en: 'tax',         es: 'impuesto'        },
      { id: 'p070', en: 'net worth',   es: 'patrimonio neto' },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  TECNOLOGÍA  (p071 – p090)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-tech',
    title: 'Tecnología',
    icon: '💻',
    color: '#ce82ff',
    colorDark: '#9b44d4',
    desc: 'Computadoras · Internet · Apps',
    vocabulary: [
      { id: 'p071', en: 'software',   es: 'software'               },
      { id: 'p072', en: 'hardware',   es: 'hardware'               },
      { id: 'p073', en: 'algorithm',  es: 'algoritmo'              },
      { id: 'p074', en: 'database',   es: 'base de datos'          },
      { id: 'p075', en: 'network',    es: 'red'                    },
      { id: 'p076', en: 'server',     es: 'servidor'               },
      { id: 'p077', en: 'cloud',      es: 'nube'                   },
      { id: 'p078', en: 'password',   es: 'contraseña'             },
      { id: 'p079', en: 'screen',     es: 'pantalla'               },
      { id: 'p080', en: 'keyboard',   es: 'teclado'                },
      { id: 'p081', en: 'app',        es: 'aplicación'             },
      { id: 'p082', en: 'download',   es: 'descargar'              },
      { id: 'p083', en: 'upload',     es: 'subir'                  },
      { id: 'p084', en: 'update',     es: 'actualización'          },
      { id: 'p085', en: 'bug',        es: 'error de programación'  },
      { id: 'p086', en: 'backup',     es: 'copia de seguridad'     },
      { id: 'p087', en: 'website',    es: 'sitio web'              },
      { id: 'p088', en: 'browser',    es: 'navegador'              },
      { id: 'p089', en: 'search',     es: 'buscar'                 },
      { id: 'p090', en: 'wireless',   es: 'inalámbrico'            },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  VIAJES  (p091 – p110)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-travel',
    title: 'Viajes',
    icon: '✈️',
    color: '#ff4b4b',
    colorDark: '#cc2222',
    desc: 'Aeropuertos · Hoteles · Turismo',
    vocabulary: [
      { id: 'p091', en: 'passport',    es: 'pasaporte'    },
      { id: 'p092', en: 'visa',        es: 'visa'         },
      { id: 'p093', en: 'flight',      es: 'vuelo'        },
      { id: 'p094', en: 'airport',     es: 'aeropuerto'   },
      { id: 'p095', en: 'reservation', es: 'reserva'      },
      { id: 'p096', en: 'ticket',      es: 'boleto'       },
      { id: 'p097', en: 'luggage',     es: 'equipaje'     },
      { id: 'p098', en: 'customs',     es: 'aduana'       },
      { id: 'p099', en: 'border',      es: 'frontera'     },
      { id: 'p100', en: 'tour guide',  es: 'guía turístico'},
      { id: 'p101', en: 'souvenir',    es: 'recuerdo'     },
      { id: 'p102', en: 'currency',    es: 'moneda'       },
      { id: 'p103', en: 'departure',   es: 'salida'       },
      { id: 'p104', en: 'arrival',     es: 'llegada'      },
      { id: 'p105', en: 'delay',       es: 'demora'       },
      { id: 'p106', en: 'connection',  es: 'conexión'     },
      { id: 'p107', en: 'check-in',    es: 'registro'     },
      { id: 'p108', en: 'boarding',    es: 'embarque'     },
      { id: 'p109', en: 'itinerary',   es: 'itinerario'   },
      { id: 'p110', en: 'insurance',   es: 'seguro'       },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  TRABAJO  (p111 – p130)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-work',
    title: 'El trabajo',
    icon: '💼',
    color: '#ffc800',
    colorDark: '#d4a000',
    desc: 'Oficina · Carrera · Reuniones',
    vocabulary: [
      { id: 'p111', en: 'office',        es: 'oficina'           },
      { id: 'p112', en: 'meeting',       es: 'reunión'           },
      { id: 'p113', en: 'deadline',      es: 'fecha límite'      },
      { id: 'p114', en: 'report',        es: 'informe'           },
      { id: 'p115', en: 'salary',        es: 'salario'           },
      { id: 'p116', en: 'bonus',         es: 'bonificación'      },
      { id: 'p117', en: 'promotion',     es: 'ascenso'           },
      { id: 'p118', en: 'interview',     es: 'entrevista'        },
      { id: 'p119', en: 'resume',        es: 'currículum'        },
      { id: 'p120', en: 'colleague',     es: 'colega'            },
      { id: 'p121', en: 'manager',       es: 'gerente'           },
      { id: 'p122', en: 'employee',      es: 'empleado'          },
      { id: 'p123', en: 'task',          es: 'tarea'             },
      { id: 'p124', en: 'project',       es: 'proyecto'          },
      { id: 'p125', en: 'presentation',  es: 'presentación'      },
      { id: 'p126', en: 'client',        es: 'cliente'           },
      { id: 'p127', en: 'contract',      es: 'contrato'          },
      { id: 'p128', en: 'training',      es: 'capacitación'      },
      { id: 'p129', en: 'feedback',      es: 'retroalimentación' },
      { id: 'p130', en: 'goal',          es: 'objetivo'          },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  DEPORTES  (p131 – p150)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-sports',
    title: 'Deportes',
    icon: '⚽',
    color: '#58cc02',
    colorDark: '#3d9900',
    desc: 'Fútbol · Tenis · Competencia',
    vocabulary: [
      { id: 'p131', en: 'soccer',        es: 'fútbol'        },
      { id: 'p132', en: 'basketball',    es: 'baloncesto'    },
      { id: 'p133', en: 'tennis',        es: 'tenis'         },
      { id: 'p134', en: 'swimming',      es: 'natación'      },
      { id: 'p135', en: 'running',       es: 'carrera'       },
      { id: 'p136', en: 'team',          es: 'equipo'        },
      { id: 'p137', en: 'player',        es: 'jugador'       },
      { id: 'p138', en: 'coach',         es: 'entrenador'    },
      { id: 'p139', en: 'score',         es: 'puntaje'       },
      { id: 'p140', en: 'championship',  es: 'campeonato'    },
      { id: 'p141', en: 'tournament',    es: 'torneo'        },
      { id: 'p142', en: 'stadium',       es: 'estadio'       },
      { id: 'p143', en: 'referee',       es: 'árbitro'       },
      { id: 'p144', en: 'trophy',        es: 'trofeo'        },
      { id: 'p145', en: 'match',         es: 'partido'       },
      { id: 'p146', en: 'race',          es: 'carrera'       },
      { id: 'p147', en: 'gym',           es: 'gimnasio'      },
      { id: 'p148', en: 'exercise',      es: 'ejercicio'     },
      { id: 'p149', en: 'fan',           es: 'hincha'        },
      { id: 'p150', en: 'champion',      es: 'campeón'       },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  ROPA  (p151 – p170)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-clothes',
    title: 'Ropa y moda',
    icon: '👔',
    color: '#ce82ff',
    colorDark: '#9b44d4',
    desc: 'Prendas · Accesorios · Estilo',
    vocabulary: [
      { id: 'p151', en: 'suit',      es: 'traje'       },
      { id: 'p152', en: 'tie',       es: 'corbata'     },
      { id: 'p153', en: 'blazer',    es: 'blazer'      },
      { id: 'p154', en: 'coat',      es: 'abrigo'      },
      { id: 'p155', en: 'hoodie',    es: 'sudadera'    },
      { id: 'p156', en: 'shorts',    es: 'shorts'      },
      { id: 'p157', en: 'tights',    es: 'medias'      },
      { id: 'p158', en: 'scarf',     es: 'bufanda'     },
      { id: 'p159', en: 'gloves',    es: 'guantes'     },
      { id: 'p160', en: 'cap',       es: 'gorra'       },
      { id: 'p161', en: 'belt',      es: 'cinturón'    },
      { id: 'p162', en: 'zipper',    es: 'cremallera'  },
      { id: 'p163', en: 'pocket',    es: 'bolsillo'    },
      { id: 'p164', en: 'sleeve',    es: 'manga'       },
      { id: 'p165', en: 'collar',    es: 'cuello'      },
      { id: 'p166', en: 'size',      es: 'talla'       },
      { id: 'p167', en: 'brand',     es: 'marca'       },
      { id: 'p168', en: 'fashion',   es: 'moda'        },
      { id: 'p169', en: 'cotton',    es: 'algodón'     },
      { id: 'p170', en: 'leather',   es: 'cuero'       },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  COMIDA AVANZADA  (p171 – p190)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-food',
    title: 'Comida avanzada',
    icon: '🍽️',
    color: '#ff9600',
    colorDark: '#d47000',
    desc: 'Sabores · Cocina · Ingredientes',
    vocabulary: [
      { id: 'p171', en: 'recipe',       es: 'receta'        },
      { id: 'p172', en: 'ingredient',   es: 'ingrediente'   },
      { id: 'p173', en: 'flavor',       es: 'sabor'         },
      { id: 'p174', en: 'spicy',        es: 'picante'       },
      { id: 'p175', en: 'sour',         es: 'ácido'         },
      { id: 'p176', en: 'bitter',       es: 'amargo'        },
      { id: 'p177', en: 'salty',        es: 'salado'        },
      { id: 'p178', en: 'fresh',        es: 'fresco'        },
      { id: 'p179', en: 'organic',      es: 'orgánico'      },
      { id: 'p180', en: 'portion',      es: 'porción'       },
      { id: 'p181', en: 'chef',         es: 'chef'          },
      { id: 'p182', en: 'seafood',      es: 'mariscos'      },
      { id: 'p183', en: 'snack',        es: 'merienda'      },
      { id: 'p184', en: 'beverage',     es: 'bebida'        },
      { id: 'p185', en: 'cuisine',      es: 'cocina'        },
      { id: 'p186', en: 'grilled',      es: 'a la parrilla' },
      { id: 'p187', en: 'roasted',      es: 'asado'         },
      { id: 'p188', en: 'raw',          es: 'crudo'         },
      { id: 'p189', en: 'boiled',       es: 'hervido'       },
      { id: 'p190', en: 'seasoning',    es: 'condimento'    },
    ],
  },

  // ─────────────────────────────────────────────────────
  //  ABREVIATURAS  (p191 – p205)
  // ─────────────────────────────────────────────────────
  {
    id: 'pack-abbrev',
    title: 'Abreviaturas',
    icon: '📝',
    color: '#1cb0f6',
    colorDark: '#0a85c0',
    desc: 'ASAP · FYI · BTW y más',
    vocabulary: [
      { id: 'p191', en: 'ASAP',  es: 'lo antes posible'          },
      { id: 'p192', en: 'FYI',   es: 'para tu información'       },
      { id: 'p193', en: 'BTW',   es: 'por cierto'                },
      { id: 'p194', en: 'AKA',   es: 'también conocido como'     },
      { id: 'p195', en: 'FAQ',   es: 'preguntas frecuentes'      },
      { id: 'p196', en: 'CEO',   es: 'director ejecutivo'        },
      { id: 'p197', en: 'HR',    es: 'recursos humanos'          },
      { id: 'p198', en: 'e.g.',  es: 'por ejemplo'               },
      { id: 'p199', en: 'i.e.',  es: 'es decir'                  },
      { id: 'p200', en: 'TBD',   es: 'por determinar'            },
      { id: 'p201', en: 'N/A',   es: 'no aplica'                 },
      { id: 'p202', en: 'P.S.',  es: 'posdata'                   },
      { id: 'p203', en: 'DIY',   es: 'hazlo tú mismo'            },
      { id: 'p204', en: 'ETA',   es: 'hora estimada de llegada'  },
      { id: 'p205', en: 'RSVP',  es: 'confirmar asistencia'      },
    ],
  },
];
